/**
 * Perlin Noise Library for JavaScript (Acode AI Assistant Optimized)
 *
 * This library provides functions to generate Perlin noise in 1D, 2D, and 3D.
 * It's designed to be simple, efficient, and suitable for use in Acode projects.
 *
 * @version 1.0.0
 * @author [Your Name or Organization] (Generated by AI Assistant for Acode)
 * @license MIT
 */

const PerlinNoise = {
  /**
   * Random seed.  Change this to get a different noise pattern.
   * Defaults to a fixed value for consistency.
   */
  seed: Math.floor(Math.random() * 0xffffff),

  /**
   * Sets the seed for the Perlin noise generator.
   * @param {number} newSeed The new seed value.  Must be an integer.
   */
  setSeed: function(newSeed) {
    if (typeof newSeed !== 'number' || !Number.isInteger(newSeed)) {
      console.warn("PerlinNoise.setSeed: Seed must be an integer. Ignoring.");
      return;
    }
    this.seed = newSeed;
  },

  /**
   * Generates a pseudo-random value between 0 and 1.
   * This uses a simple LCG (Linear Congruential Generator)
   * which is adequate for this purpose.  Consider a more robust
   * PRNG if security is important.
   * @param {number} a The input number.
   * @returns {number} A pseudo-random number between 0 and 1.
   * @private
   */
  _random: function(a) {
    const x = Math.sin(a + this.seed) * 10000;
    return x - Math.floor(x);
  },


  /**
   * Linear interpolation function.
   * @param {number} a The first value.
   * @param {number} b The second value.
   * @param {number} t The interpolation factor (0-1).
   * @returns {number} The interpolated value.
   * @private
   */
  _lerp: function(a, b, t) {
    return a + t * (b - a);
  },


  /**
   * Smoother interpolation function (using cosine).
   *  Gives smoother results than linear interpolation.
   * @param {number} a The first value.
   * @param {number} b The second value.
   * @param {number} t The interpolation factor (0-1).
   * @returns {number} The smoothed interpolated value.
   * @private
   */
  _smooth: function(a, b, t) {
    const factor = (1 - Math.cos(t * Math.PI)) / 2;
    return a + factor * (b - a);
  },



  /**
   * Generates 1D Perlin noise.
   * @param {number} x The x coordinate.
   * @param {number} frequency The frequency of the noise (higher values create more rapid changes). Defaults to 1.
   * @param {number} amplitude The amplitude (scale) of the noise. Defaults to 1.
   * @param {number} octaves The number of octaves to use (for fractal noise). Defaults to 1.
   * @param {number} persistence The persistence of each octave (0-1).  Lower values mean each octave contributes less.  Defaults to 0.5.
   * @returns {number} The Perlin noise value (between -amplitude and amplitude, generally).
   */
  noise1D: function(x, frequency = 1, amplitude = 1, octaves = 1, persistence = 0.5) {
      let total = 0;
      let maxAmplitude = 0;

      for (let i = 0; i < octaves; i++) {
          const freq = frequency * Math.pow(2, i);
          const amp = amplitude * Math.pow(persistence, i);
          total += this._noise1DInternal(x * freq) * amp;
          maxAmplitude += amp;
      }

      return total / maxAmplitude; // Normalize the result
  },


  /**
   * Internal 1D noise function.  Handles the core Perlin noise logic.
   * @param {number} x The x coordinate.
   * @returns {number} The noise value.
   * @private
   */
  _noise1DInternal: function(x) {
    const x0 = Math.floor(x);
    const x1 = x0 + 1;
    const sx = x - x0;

    const n0 = this._random(x0);
    const n1 = this._random(x1);

    return this._smooth(n0, n1, sx); // Use smooth interpolation for better results
  },




  /**
   * Generates 2D Perlin noise.
   * @param {number} x The x coordinate.
   * @param {number} y The y coordinate.
   * @param {number} frequency The frequency of the noise (higher values create more rapid changes). Defaults to 1.
   * @param {number} amplitude The amplitude (scale) of the noise. Defaults to 1.
   * @param {number} octaves The number of octaves to use (for fractal noise). Defaults to 1.
   * @param {number} persistence The persistence of each octave (0-1).  Lower values mean each octave contributes less.  Defaults to 0.5.
   * @returns {number} The Perlin noise value (between -amplitude and amplitude, generally).
   */
  noise2D: function(x, y, frequency = 1, amplitude = 1, octaves = 1, persistence = 0.5) {
    let total = 0;
    let maxAmplitude = 0;

    for (let i = 0; i < octaves; i++) {
      const freq = frequency * Math.pow(2, i);
      const amp = amplitude * Math.pow(persistence, i);
      total += this._noise2DInternal(x * freq, y * freq) * amp;
      maxAmplitude += amp;
    }

    return total / maxAmplitude; // Normalize the result.
  },



  /**
   * Internal 2D noise function.  Handles the core Perlin noise logic.
   * @param {number} x The x coordinate.
   * @param {number} y The y coordinate.
   * @returns {number} The noise value.
   * @private
   */
  _noise2DInternal: function(x, y) {
    const x0 = Math.floor(x);
    const y0 = Math.floor(y);
    const x1 = x0 + 1;
    const y1 = y0 + 1;

    const sx = x - x0;
    const sy = y - y0;


    const n00 = this._random(x0 + y0 * 57); // Using a prime number to avoid patterns
    const n10 = this._random(x1 + y0 * 57);
    const n01 = this._random(x0 + y1 * 57);
    const n11 = this._random(x1 + y1 * 57);

    const ix0 = this._smooth(n00, n10, sx);
    const ix1 = this._smooth(n01, n11, sx);

    return this._smooth(ix0, ix1, sy);
  },


  /**
   * Generates 3D Perlin noise.
   * @param {number} x The x coordinate.
   * @param {number} y The y coordinate.
   * @param {number} z The z coordinate.
   * @param {number} frequency The frequency of the noise (higher values create more rapid changes). Defaults to 1.
   * @param {number} amplitude The amplitude (scale) of the noise. Defaults to 1.
   * @param {number} octaves The number of octaves to use (for fractal noise). Defaults to 1.
   * @param {number} persistence The persistence of each octave (0-1).  Lower values mean each octave contributes less.  Defaults to 0.5.
   * @returns {number} The Perlin noise value (between -amplitude and amplitude, generally).
   */
  noise3D: function(x, y, z, frequency = 1, amplitude = 1, octaves = 1, persistence = 0.5) {
    let total = 0;
    let maxAmplitude = 0;

    for (let i = 0; i < octaves; i++) {
      const freq = frequency * Math.pow(2, i);
      const amp = amplitude * Math.pow(persistence, i);
      total += this._noise3DInternal(x * freq, y * freq, z * freq) * amp;
      maxAmplitude += amp;
    }

    return total / maxAmplitude; // Normalize the result
  },



  /**
   * Internal 3D noise function.  Handles the core Perlin noise logic.
   * @param {number} x The x coordinate.
   * @param {number} y The y coordinate.
   * @param {number} z The z coordinate.
   * @returns {number} The noise value.
   * @private
   */
  _noise3DInternal: function(x, y, z) {
    const x0 = Math.floor(x);
    const y0 = Math.floor(y);
    const z0 = Math.floor(z);
    const x1 = x0 + 1;
    const y1 = y0 + 1;
    const z1 = z0 + 1;

    const sx = x - x0;
    const sy = y - y0;
    const sz = z - z0;

    const n000 = this._random(x0 + y0 * 57 + z0 * 131); // Prime numbers
    const n100 = this._random(x1 + y0 * 57 + z0 * 131);
    const n010 = this._random(x0 + y1 * 57 + z0 * 131);
    const n110 = this._random(x1 + y1 * 57 + z0 * 131);
    const n001 = this._random(x0 + y0 * 57 + z1 * 131);
    const n101 = this._random(x1 + y0 * 57 + z1 * 131);
    const n011 = this._random(x0 + y1 * 57 + z1 * 131);
    const n111 = this._random(x1 + y1 * 57 + z1 * 131);


    const ix00 = this._smooth(n000, n100, sx);
    const ix10 = this._smooth(n010, n110, sx);
    const ix01 = this._smooth(n001, n101, sx);
    const ix11 = this._smooth(n011, n111, sx);

    const ixy0 = this._smooth(ix00, ix10, sy);
    const ixy1 = this._smooth(ix01, ix11, sy);

    return this._smooth(ixy0, ixy1, sz);
  }
};


// Example usage (can be removed or commented out for library use)
/*
// Set the seed
PerlinNoise.setSeed(12345);

// 1D Example
for (let i = 0; i < 10; i++){
    console.log("1D Noise at " + i + ": " + PerlinNoise.noise1D(i, 0.1));
}

// 2D Example (Generate a 10x10 grid of noise values)
console.log("2D Noise:")
for (let y = 0; y < 10; y++) {
    let row = "";
    for (let x = 0; x < 10; x++) {
        row += PerlinNoise.noise2D(x, y, 0.1).toFixed(2) + " ";
    }
    console.log(row);
}

// 3D Example
console.log("3D Noise at (1,1,1): " + PerlinNoise.noise3D(1, 1, 1, 0.1));

*/


